### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Anisha7** [MakeMeSenpai/checklist#1]
Great work on these challenges! Here's some feedback to further improve your code:
- Your select function is passing in ‘user_input’ function into the create function when calling it instead of the item. Also calling things item_index is quite confusing! Index is used for the number/location of the item in the array and item is the actual item in string format. 
- Also, why are you using time.sleep() ? It slows down your program.
- Your call to read in select does not work because all user_input returned values are string. You need to covert this to an int.
- You are missing your test() function! Write some tests to see if your functions are working as expected! This is required.
- Come to office hours for further debugging help!

**Comment by The1stAnthony** [comment]
- changed item_index to 'item'. 
- removed lag by removing sleep
- changed user_input into int on line 72 when defined as item
